"""Role-prefixed workspace URLs, e.g. /it-support/dashboard/."""

from django.urls import path

from . import role_dashboards

app_name = "roles"

urlpatterns = [
    path("super-admin/dashboard/", role_dashboards.super_admin_dashboard, name="super_admin"),
    path("super-admin/clients/", role_dashboards.super_admin_clients, name="super_admin_clients"),
    path(
        "super-admin/clients/<int:pk>/edit/",
        role_dashboards.super_admin_client_edit,
        name="super_admin_client_edit",
    ),
    path(
        "super-admin/clients/<int:pk>/suspend/",
        role_dashboards.super_admin_client_suspend,
        name="super_admin_client_suspend",
    ),
    path(
        "super-admin/clients/<int:pk>/unsuspend/",
        role_dashboards.super_admin_client_unsuspend,
        name="super_admin_client_unsuspend",
    ),
    path(
        "super-admin/clients/<int:pk>/delete/",
        role_dashboards.super_admin_client_delete,
        name="super_admin_client_delete",
    ),
    path(
        "super-admin/human-resources/",
        role_dashboards.super_admin_hr,
        name="super_admin_hr",
    ),
    path(
        "super-admin/human-resources/<int:pk>/edit/",
        role_dashboards.super_admin_hr_edit,
        name="super_admin_hr_edit",
    ),
    path(
        "super-admin/human-resources/<int:pk>/suspend/",
        role_dashboards.super_admin_hr_suspend,
        name="super_admin_hr_suspend",
    ),
    path(
        "super-admin/human-resources/<int:pk>/unsuspend/",
        role_dashboards.super_admin_hr_unsuspend,
        name="super_admin_hr_unsuspend",
    ),
    path(
        "super-admin/human-resources/<int:pk>/delete/",
        role_dashboards.super_admin_hr_delete,
        name="super_admin_hr_delete",
    ),
    path("administrator/dashboard/", role_dashboards.administrator_dashboard, name="administrator"),
    path("administrator/clients/", role_dashboards.administrator_clients, name="administrator_clients"),
    path(
        "administrator/human-resources/",
        role_dashboards.administrator_hr,
        name="administrator_hr",
    ),
    path("customer-support/dashboard/", role_dashboards.manager_dashboard, name="customer_support"),
    path(
        "customer-support/isp-clients/",
        role_dashboards.manager_isp_clients,
        name="customer_support_isp_clients",
    ),
    path(
        "customer-support/isp-clients/<int:pk>/open-portal/",
        role_dashboards.manager_open_client_portal,
        name="customer_support_open_client_portal",
    ),
    path(
        "customer-support/exit-client-portal/",
        role_dashboards.manager_exit_client_portal,
        name="customer_support_exit_client_portal",
    ),
    path(
        "customer-support/sales/",
        role_dashboards.manager_sales,
        name="customer_support_sales",
    ),
    path(
        "customer-support/approved-sales/",
        role_dashboards.manager_approved_sales,
        name="customer_support_approved_sales",
    ),
    path(
        "customer-support/technician/",
        role_dashboards.manager_technician,
        name="customer_support_technician",
    ),
    path(
        "customer-support/allocated/",
        role_dashboards.manager_allocated,
        name="customer_support_allocated",
    ),
    path(
        "customer-support/network-equipment/",
        role_dashboards.manager_network_equipment,
        name="customer_support_network_equipment",
    ),
    path(
        "customer-support/allocate/",
        role_dashboards.manager_allocate,
        name="customer_support_allocate",
    ),
    path(
        "customer-support/allocate/<int:pk>/",
        role_dashboards.manager_allocate_employee,
        name="customer_support_allocate_employee",
    ),
    # Legacy manager paths redirect via same views (compat aliases).
    path("manager/dashboard/", role_dashboards.manager_dashboard, name="manager"),
    path(
        "manager/isp-clients/",
        role_dashboards.manager_isp_clients,
        name="manager_isp_clients",
    ),
    path(
        "manager/sales/",
        role_dashboards.manager_sales,
        name="manager_sales",
    ),
    path(
        "manager/approved-sales/",
        role_dashboards.manager_approved_sales,
        name="manager_approved_sales",
    ),
    path(
        "manager/technician/",
        role_dashboards.manager_technician,
        name="manager_technician",
    ),
    path(
        "manager/allocated/",
        role_dashboards.manager_allocated,
        name="manager_allocated",
    ),
    path(
        "manager/network-equipment/",
        role_dashboards.manager_network_equipment,
        name="manager_network_equipment",
    ),
    path(
        "manager/allocate/",
        role_dashboards.manager_allocate,
        name="manager_allocate",
    ),
    path(
        "manager/allocate/<int:pk>/",
        role_dashboards.manager_allocate_employee,
        name="manager_allocate_employee",
    ),
    path("it-support/dashboard/", role_dashboards.it_support_dashboard, name="it_support"),
    path(
        "it-support/company-clients/",
        role_dashboards.it_support_company_clients,
        name="it_support_company_clients",
    ),
    path(
        "it-support/company-clients/<int:pk>/edit/",
        role_dashboards.it_support_company_client_edit,
        name="it_support_company_client_edit",
    ),
    path(
        "it-support/company-clients/<int:pk>/suspend/",
        role_dashboards.it_support_company_client_suspend,
        name="it_support_company_client_suspend",
    ),
    path(
        "it-support/company-clients/<int:pk>/unsuspend/",
        role_dashboards.it_support_company_client_unsuspend,
        name="it_support_company_client_unsuspend",
    ),
    path(
        "it-support/company-clients/<int:pk>/delete/",
        role_dashboards.it_support_company_client_delete,
        name="it_support_company_client_delete",
    ),
    path(
        "it-support/human-resources/",
        role_dashboards.it_support_hr,
        name="it_support_hr",
    ),
    path(
        "it-support/human-resources/<int:pk>/edit/",
        role_dashboards.it_support_hr_edit,
        name="it_support_hr_edit",
    ),
    path(
        "it-support/human-resources/<int:pk>/suspend/",
        role_dashboards.it_support_hr_suspend,
        name="it_support_hr_suspend",
    ),
    path(
        "it-support/human-resources/<int:pk>/unsuspend/",
        role_dashboards.it_support_hr_unsuspend,
        name="it_support_hr_unsuspend",
    ),
    path(
        "it-support/human-resources/<int:pk>/delete/",
        role_dashboards.it_support_hr_delete,
        name="it_support_hr_delete",
    ),
    path(
        "it-support/payment-gateway/",
        role_dashboards.it_support_payment_gateway,
        name="it_support_payment_gateway",
    ),
    path(
        "it-support/payment-gateway/status/",
        role_dashboards.it_support_payment_gateway_status,
        name="it_support_payment_gateway_status",
    ),
    path(
        "it-support/company-settings/",
        role_dashboards.it_support_company_settings,
        name="it_support_company_settings",
    ),
    path(
        "it-support/company-settings/communications/",
        role_dashboards.it_support_company_communications,
        name="it_support_company_communications",
    ),
    path(
        "it-support/company-settings/communications/fetch/",
        role_dashboards.it_support_company_communications_fetch,
        name="it_support_company_communications_fetch",
    ),
    path(
        "it-support/commissions/",
        role_dashboards.it_support_commissions,
        name="it_support_commissions",
    ),
    path(
        "it-support/commissions/<slug:role_slug>/",
        role_dashboards.it_support_commission_role,
        name="it_support_commission_role",
    ),
    path(
        "it-support/system-settings/",
        role_dashboards.it_support_system_settings,
        name="it_support_system_settings",
    ),
    path(
        "it-support/system-settings/communications/",
        role_dashboards.it_support_settings_communications,
        name="it_support_settings_communications",
    ),
    path(
        "it-support/system-settings/payments/",
        role_dashboards.it_support_settings_payments,
        name="it_support_settings_payments",
    ),
    path(
        "it-support/client-settings/",
        role_dashboards.it_support_client_settings,
        name="it_support_client_settings",
    ),
    path("it-support/switch-role/", role_dashboards.switch_role_view, name="switch_role"),
    path("sales/dashboard/", role_dashboards.sales_dashboard, name="sales"),
    path(
        "sales/lead-management/",
        role_dashboards.sales_lead_management,
        name="sales_lead_management",
    ),
    path(
        "sales/places/",
        role_dashboards.sales_places,
        name="sales_places",
    ),
    path(
        "sales/places/details/",
        role_dashboards.sales_place_details,
        name="sales_place_details",
    ),
    path(
        "sales/customer-registration/",
        role_dashboards.sales_customer_registration,
        name="sales_customer_registration",
    ),
    path(
        "sales/sales-orders/",
        role_dashboards.sales_orders,
        name="sales_orders",
    ),
    path(
        "sales/installation-requests/",
        role_dashboards.sales_installation_requests,
        name="sales_installation_requests",
    ),
    path(
        "sales/promotions-discounts/",
        role_dashboards.sales_promotions_discounts,
        name="sales_promotions_discounts",
    ),
    path(
        "sales/commissions/",
        role_dashboards.sales_commissions,
        name="sales_commissions",
    ),
    path(
        "sales/reports/",
        role_dashboards.sales_reports,
        name="sales_reports",
    ),
    path("technician/dashboard/", role_dashboards.technician_dashboard, name="technician"),
    path(
        "technician/installations/",
        role_dashboards.technician_installations,
        name="technician_installations",
    ),
    path(
        "technician/installations/<int:customer_id>/accept/",
        role_dashboards.technician_installation_accept,
        name="technician_installation_accept",
    ),
    path(
        "technician/installations/<int:customer_id>/not-interested/",
        role_dashboards.technician_installation_not_interested,
        name="technician_installation_not_interested",
    ),
    path(
        "technician/installations/<int:customer_id>/reject/",
        role_dashboards.technician_installation_reject,
        name="technician_installation_reject",
    ),
    path(
        "technician/fault-tickets/",
        role_dashboards.technician_fault_tickets,
        name="technician_fault_tickets",
    ),
    path(
        "technician/network-equipment/",
        role_dashboards.technician_network_equipment,
        name="technician_network_equipment",
    ),
]
