# Generated by Django 4.2.30 on 2026-07-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_org_status_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('pppoe', 'PPPoE'), ('static', 'Static'), ('hotspot', 'Hotspot')], db_index=True, default='pppoe', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'service_type'], name='bill_cust_org_svc_idx'),
        ),
    ]
