# Generated by Django 4.2.30 on 2026-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customer_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='PPPoE password'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pppoe_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='PPPoE username'),
        ),
    ]
