# Generated by Django 4.2.30 on 2026-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_customer_pppoe_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional package image shown on billing screens.', null=True, upload_to='billing/packages/%Y/%m/', verbose_name='Package image'),
        ),
    ]
