# Generated by Django 4.2.30 on 2026-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='duration',
            field=models.CharField(choices=[('hourly', 'Per hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
