# Generated by Django 4.2.30 on 2026-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billingplan_hourly_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='download_speed_mbps',
            field=models.PositiveIntegerField(default=10, verbose_name='Download speed (Mbps)'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='upload_speed_mbps',
            field=models.PositiveIntegerField(default=5, verbose_name='Upload speed (Mbps)'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='speed_mbps',
            field=models.PositiveIntegerField(default=10, help_text='Derived from download/upload speeds for summaries and legacy displays.', verbose_name='General speed (Mbps)'),
        ),
    ]
