# Generated by Django 4.2.30 on 2026-07-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mikrotik_internet_provider'),
        ('billing', '0007_billingplan_download_upload_speeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='router',
            field=models.ForeignKey(blank=True, help_text='MikroTik this client is provisioned on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.mikrotikrouter'),
        ),
    ]
