# Generated by Django 4.2.30 on 2026-07-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_customer_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_start',
            field=models.DateField(blank=True, help_text='First day of the current paid surfing period.', null=True, verbose_name='Service start'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_until',
            field=models.DateField(blank=True, help_text='Last day of the current paid surfing period.', null=True, verbose_name='Service until'),
        ),
    ]
