# Generated by Django 4.2.30 on 2026-07-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_customer_service_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paused_at',
            field=models.DateField(blank=True, help_text='Date the subscription was paused.', null=True, verbose_name='Paused on'),
        ),
        migrations.AddField(
            model_name='customer',
            name='paused_days_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Inclusive paid days frozen while the subscription is paused.', null=True, verbose_name='Paused days remaining'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
