# Generated by Django 4.2.30 on 2026-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_customer_subscription_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, help_text='Last day of the billed surfing cycle.', null=True, verbose_name='Billing period end'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, help_text='First day of the billed surfing cycle.', null=True, verbose_name='Billing period start'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'period_start', 'period_end'], name='bill_inv_cust_period_idx'),
        ),
    ]
