# Generated by Django 5.0.14 on 2026-07-27 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organization_pppoe_compulsory'),
        ('billing', '0010_customer_package_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-issued_at'], name='bill_inv_cust_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'customer'], name='bill_inv_org_cust_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'received_at'], name='bill_pay_org_recv_idx'),
        ),
    ]
