# Generated by Django 5.0.14 on 2026-08-01 05:14

from django.db import migrations, models


def dedupe_hotspot_macs(apps, schema_editor):
    """Keep the oldest Hotspot customer per org+MAC; blank newer duplicates."""
    Customer = apps.get_model("billing", "Customer")
    seen = set()
    qs = (
        Customer.objects.filter(service_type="hotspot")
        .exclude(hotspot_mac="")
        .order_by("organization_id", "hotspot_mac", "id")
    )
    for customer in qs.iterator():
        key = (customer.organization_id, (customer.hotspot_mac or "").upper())
        if key in seen:
            customer.hotspot_mac = ""
            customer.save(update_fields=["hotspot_mac"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_customer_hotspot_mac"),
        ("core", "0012_mikrotik_serial_number"),
    ]

    operations = [
        migrations.RunPython(dedupe_hotspot_macs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("service_type", "hotspot"),
                    models.Q(("hotspot_mac", ""), _negated=True),
                ),
                fields=("organization", "hotspot_mac"),
                name="bill_cust_org_hotspot_mac_uniq",
            ),
        ),
    ]
