# Generated by Django 5.0.14 on 2026-08-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customer_hotspot_mac_unique'),
        ('billing', '0017_stkpushrequest_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUsageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(db_index=True)),
                ('session_active', models.BooleanField(default=False)),
                ('uptime_seconds', models.PositiveIntegerField(default=0)),
                ('download_bps', models.BigIntegerField(default=0)),
                ('upload_bps', models.BigIntegerField(default=0)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_samples', to='billing.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_usage_samples', to='accounts.organization')),
            ],
            options={
                'db_table': 'billing_customer_usage_sample',
                'ordering': ['sampled_at'],
                'indexes': [models.Index(fields=['customer', 'sampled_at'], name='bill_usage_cust_sampled_idx'), models.Index(fields=['organization', 'sampled_at'], name='bill_usage_org_sampled_idx')],
            },
        ),
    ]
