# Generated by Django 5.0.14 on 2026-08-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customer_organization_optional'),
        ('billing', '0018_customer_usage_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='ISP this client belongs to. Optional until a specific provider is assigned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.organization'),
        ),
    ]
