# Generated by Django 5.0.14 on 2026-08-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_sales_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('allocated', 'Allocated'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
