# Generated by Django 5.0.14 on 2026-08-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_role_commission_package_percent'),
        ('billing', '0028_customer_allocated_open_closed_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='declined_by_technicians',
            field=models.ManyToManyField(blank=True, help_text='Technicians who marked this installation ticket as not interested.', related_name='declined_installation_customers', to='accounts.employee'),
        ),
    ]
