# Generated by Django 5.0.14 on 2026-08-02 07:29

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_declines(apps, schema_editor):
    Customer = apps.get_model("billing", "Customer")
    InstallationDecline = apps.get_model("billing", "InstallationDecline")
    through = Customer.declined_by_technicians.through
    for row in through.objects.all().iterator():
        InstallationDecline.objects.get_or_create(
            customer_id=row.customer_id,
            technician_id=row.employee_id,
            defaults={
                "reason_category": "other",
                "reason": "Other reason: Migrated from previous hide",
            },
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_role_commission_package_percent"),
        ("billing", "0029_customer_declined_by_technicians"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationDecline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("too_far", "Too far / wrong location"),
                            ("no_capacity", "No capacity / too busy"),
                            ("site_not_ready", "Site not ready"),
                            ("access_issue", "Access / security issue"),
                            ("other", "Other reason"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installation_declines",
                        to="billing.customer",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installation_declines",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "db_table": "billing_installation_decline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="installationdecline",
            constraint=models.UniqueConstraint(
                fields=("customer", "technician"),
                name="bill_inst_decline_cust_tech_uniq",
            ),
        ),
        migrations.RunPython(forwards_copy_declines, backwards_noop),
        migrations.RemoveField(
            model_name="customer",
            name="declined_by_technicians",
        ),
    ]
