# Generated by Django 5.0.14 on 2026-08-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_role_commission_package_percent'),
        ('billing', '0030_installation_decline_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('too_far', 'Too far / wrong location'), ('no_capacity', 'No capacity / too busy'), ('site_not_ready', 'Site not ready'), ('access_issue', 'Access / security issue'), ('client_unavailable', 'Client unavailable'), ('other', 'Other reason')], max_length=40)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_rejects', to='billing.customer')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_rejects', to='accounts.employee')),
            ],
            options={
                'db_table': 'billing_installation_reject',
                'ordering': ['-created_at'],
            },
        ),
    ]
