# Generated by Django 4.2.30 on 2026-08-25 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_billingplan_package_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='max_devices',
            field=models.PositiveIntegerField(default=0, help_text='How many Hotspot devices this package allows. 0 / blank = unlimited. Hotspot: phones/laptops on one paid account. PPPoE always enforces 1 concurrent dial (one CPE); LAN behind it is unlimited.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Max devices'),
        ),
    ]
