# Generated by Django 6.1 on 2026-08-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_paymentgateway_callback_url'),
        ('billing', '0044_alter_billingplan_max_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessvoucher',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Cash/bank recharge that issued this voucher batch (when no STK).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_vouchers', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='accessvoucher',
            name='subscription_applied',
            field=models.BooleanField(default=False, help_text='True when the paid package for this voucher was already extended (cash recharge or STK activate).'),
        ),
        migrations.AddIndex(
            model_name='accessvoucher',
            index=models.Index(fields=['payment', 'status'], name='bill_voucher_pay_status_idx'),
        ),
    ]
