# Generated by Django 6.1 on 2026-08-30 18:06

import ispcentric.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_accessvoucher_payment_and_subscription_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpe_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text="RouterOS / Winbox password on the client's CPE router.", max_length=512, verbose_name='CPE password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpe_wifi_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='CPE Wi‑Fi password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pppoe_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='PPPoE password'),
        ),
    ]
