# Generated by Django 5.0.14 on 2026-09-16 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0053_customer_usage_tracking_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvoucher',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Subscriber this voucher was issued for. Cleared if the client is deleted; the voucher stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_vouchers', to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Subscriber this invoice was issued to. Cleared if the client is deleted; the invoice stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='stkpushrequest',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional for platform fees such as MikroTik onboarding. Cleared if the client is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_push_requests', to='billing.customer'),
        ),
    ]
