# Generated by Django 5.0.14 on 2026-09-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_organization_dpo_contact_and_comms'),
        ('billing', '0056_billingplan_guaranteed_speeds'),
        ('core', '0027_mikrotikrouter_uplink_capacity_mbps'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotConnectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, db_index=True, max_length=17)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('event', models.CharField(choices=[('portal_hit', 'Portal visit'), ('payment_started', 'Payment attempted'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_cancelled', 'Payment cancelled'), ('authorized', 'Connected (surfing)'), ('paid_not_surfing', 'Paid but not surfing')], db_index=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_connection_attempts', to='billing.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_connection_attempts', to='accounts.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_connection_attempts', to='billing.billingplan')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_connection_attempts', to='core.mikrotikrouter')),
                ('stk_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_attempts', to='billing.stkpushrequest')),
            ],
            options={
                'db_table': 'billing_hotspot_connection_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event', '-created_at'], name='bill_hs_att_org_evt_idx'), models.Index(fields=['organization', 'mac', '-created_at'], name='bill_hs_att_org_mac_idx')],
            },
        ),
    ]
