# Generated by Django 5.0.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0058_hotspot_other_devices_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerusagesample",
            name="network_connected",
            field=models.BooleanField(default=False),
        ),
    ]
