# Generated by Django 5.0.14 on 2026-09-22 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_customerusagesample_network_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='hotspot_hourly_rate_per_device',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KES per hour per device: total = base + (rate × devices × hours).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hourly rate per device'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='hotspot_other_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base KES fee before hourly top-up for other-device purchases. Blank = use package price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other devices base price'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='hotspot_other_devices_enabled',
            field=models.BooleanField(default=True, help_text='Offer “Pay for other devices” on the captive page with hourly multi-device voucher pricing.', verbose_name='Hotspot other-devices pay'),
        ),
    ]
