# Generated by Django 5.0.14 on 2026-10-01 02:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_alter_billingplan_hotspot_fields_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='fup_action',
            field=models.CharField(choices=[('disconnect', 'Disconnect until period resets'), ('throttle', 'Throttle speed until period resets')], default='throttle', help_text='What happens when a client hits the FUP data limit.', max_length=20, verbose_name='FUP action'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_data_limit_gb',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum data (download + upload) one client may use in each FUP period.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='FUP data limit (GB)'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, each client on this package is limited to a data cap per FUP period.', verbose_name='Fair usage policy enabled'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_period_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', help_text='Unit for the fair-usage reset window (hours, days, weeks, months, or years).', max_length=10, verbose_name='FUP period unit'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_period_value',
            field=models.PositiveIntegerField(default=1, help_text='How many units the fair-usage window lasts before it resets.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='FUP period length'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_throttle_download_mbps',
            field=models.PositiveIntegerField(default=1, help_text='Download speed after the FUP limit is hit (throttle action only).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='FUP throttle download (Mbps)'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='fup_throttle_upload_mbps',
            field=models.PositiveIntegerField(default=1, help_text='Upload speed after the FUP limit is hit (throttle action only).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='FUP throttle upload (Mbps)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fup_bytes_used',
            field=models.BigIntegerField(default=0, help_text='Bytes counted toward the package FUP limit in the current window.', verbose_name='FUP bytes used'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fup_restricted',
            field=models.BooleanField(default=False, help_text='True when the client has hit the package FUP limit in the current window.', verbose_name='FUP restricted'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fup_restricted_at',
            field=models.DateTimeField(blank=True, help_text='When the current FUP restriction was applied.', null=True, verbose_name='FUP restricted at'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fup_window_start',
            field=models.DateTimeField(blank=True, help_text="Start of the client's current fair-usage period window.", null=True, verbose_name='FUP window start'),
        ),
    ]
