# Generated by Django 5.0.14 on 2026-10-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0061_billingplan_fup_and_customer_fup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessvoucher',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Subscriber this voucher was issued for. Client delete purges vouchers as access credentials; payment/invoice rows stay.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_vouchers', to='billing.customer'),
        ),
    ]
