# Generated by Django 4.2.30 on 2026-07-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(choices=[('hap_ax2', 'hAP ax²'), ('hap_ax3', 'hAP ax³'), ('hap_lite', 'hAP lite'), ('hap_ac2', 'hAP ac²'), ('hap_ac3', 'hAP ac³'), ('rb750gr3', 'hEX (RB750Gr3)'), ('rb760igs', 'hEX S (RB760iGS)'), ('rb4011', 'RB4011'), ('rb5009', 'RB5009'), ('ccr2004', 'CCR2004'), ('ccr2116', 'CCR2116'), ('ccr2216', 'CCR2216'), ('chr', 'Cloud Hosted Router (CHR)'), ('audience', 'Audience'), ('other', 'Other / Custom')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('host', models.CharField(help_text='Router IP address or hostname', max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_routers', to='accounts.organization')),
            ],
            options={
                'db_table': 'core_mikrotik_router',
                'ordering': ['name'],
            },
        ),
    ]
