# Generated by Django 4.2.30 on 2026-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mikrotikrouter_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='host',
            field=models.CharField(help_text='MikroTik IP address or hostname', max_length=255),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='model',
            field=models.CharField(choices=[('hap_ax2', 'hAP ax²'), ('hap_ax3', 'hAP ax³'), ('hap_lite', 'hAP lite'), ('hap_ac2', 'hAP ac²'), ('hap_ac3', 'hAP ac³'), ('rb750gr3', 'hEX'), ('rb760igs', 'hEX S'), ('l009', 'L009'), ('rb2011', 'RB2011'), ('rb3011', 'RB3011'), ('rb4011', 'RB4011'), ('rb5009', 'RB5009'), ('ccr2004', 'CCR2004'), ('ccr2116', 'CCR2116'), ('ccr2216', 'CCR2216'), ('chr', 'CHR'), ('audience', 'Audience'), ('other', 'Other')], max_length=32),
        ),
    ]
