# Generated by Django 4.2.30 on 2026-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mikrotik_wifi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
    ]
