# Generated by Django 4.2.30 on 2026-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mikrotik_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='internet_provider',
            field=models.CharField(blank=True, help_text='ISP or upstream provider feeding this MikroTik (e.g. Safaricom, Starlink).', max_length=120, verbose_name='Internet company'),
        ),
    ]
