# Generated by Django 5.0.14 on 2026-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mikrotik_uplink_unbridged'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='vpn_address',
            field=models.GenericIPAddressField(blank=True, help_text='Address this router answers on inside the WireGuard tunnel.', null=True, protocol='IPv4', unique=True, verbose_name='Tunnel address'),
        ),
        migrations.AddField(
            model_name='mikrotikrouter',
            name='vpn_private_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mikrotikrouter',
            name='vpn_public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='clean_uplink_separate_wan',
            field=models.BooleanField(default=False, help_text='Remove the WAN port from the LAN bridge so MikroTik routes instead of switching.', verbose_name='Separate WAN from bridge'),
        ),
    ]
