# Generated by Django 5.0.14 on 2026-07-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mikrotik_wireguard_peer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Site name, for your reference.', max_length=150)),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('public_key', models.CharField(max_length=64)),
                ('private_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_wireguard_reservation',
                'ordering': ['address'],
            },
        ),
    ]
