# Generated by Django 5.0.14 on 2026-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_mikrotik_serial_number'),
        ('core', '0011_wireguard_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='RouterBOARD serial from /system/routerboard — unique hardware identity.', max_length=64, verbose_name='Serial number'),
        ),
        migrations.AddField(
            model_name='mikrotikrouter',
            name='software_id',
            field=models.CharField(blank=True, help_text='RouterOS license software-id from /system/license.', max_length=64, verbose_name='Software ID'),
        ),
        migrations.AddConstraint(
            model_name='mikrotikrouter',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('organization', 'serial_number'), name='uniq_org_mikrotik_serial'),
        ),
    ]
