# Generated by Django 5.0.14 on 2026-08-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_network_equipment_allocation'),
        ('core', '0014_clean_uplink_any_isp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikStatusSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(default='disconnected', max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_status_samples', to='accounts.organization')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_samples', to='core.mikrotikrouter')),
            ],
            options={
                'db_table': 'core_mikrotik_status_sample',
                'ordering': ['sampled_at'],
                'indexes': [models.Index(fields=['organization', 'sampled_at'], name='core_mt_status_org_at_idx'), models.Index(fields=['router', 'sampled_at'], name='core_mt_status_router_at_idx')],
            },
        ),
    ]
