# Generated by Django 6.1 on 2026-08-30 18:06

import ispcentric.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mikrotik_status_sample_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='default_cpe_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='Pre-filled on new PPPoE clients; used for remote CPE access from ISPCENTRIC.', max_length=512, verbose_name='Default client router password'),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='password',
            field=ispcentric.encrypted_fields.EncryptedCharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='vpn_private_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='wifi_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Wi‑Fi password'),
        ),
        migrations.AlterField(
            model_name='wireguardreservation',
            name='private_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(max_length=512),
        ),
    ]
