# Generated by Django 5.0.14 on 2026-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_clean_uplink_soft_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='uplink_mode',
            field=models.CharField(choices=[('single', 'Single WAN'), ('bond', 'Bonded uplinks (same provider)'), ('failover', 'Failover (different providers)'), ('balance', 'Load balance (different providers)'), ('smart_balance', 'Smart balance (avoid slow ISPs)')], default='single', help_text='UI offers three setups: one link, same-ISP bond, or multiple ISPs. Multi-ISP stores as smart_balance (share + failover on every link). Legacy failover/balance values still work and map to the multi-ISP UI.', max_length=16, verbose_name='Uplink mode'),
        ),
    ]
