# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_mikrotikrouter_uplink_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="mikrotikrouter",
            name="usage_tracking_since",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Baseline for combined client usage on this MikroTik. "
                    "Historical samples are kept; totals ignore traffic before this stamp."
                ),
                null=True,
                verbose_name="Usage tracking since",
            ),
        ),
    ]
