# Generated by Django 5.0.14 on 2026-09-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0030_mikrotikrouter_smart_auto_balance_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="wireguardreservation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="ISP workspace that owns this onboarding tunnel (unique keys per tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wireguard_reservations",
                to="accounts.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="wireguardreservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "label"),
                name="core_wg_reservation_org_label_uniq",
            ),
        ),
    ]
