# Generated by Django 5.0.14 on 2026-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mikrotik_onboarding_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikonboardingsession',
            name='management_host',
            field=models.GenericIPAddressField(blank=True, help_text='LAN gateway saved on MikroTikRouter.host after commit.', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='mikrotikonboardingsession',
            name='verified_dial_host',
            field=models.GenericIPAddressField(blank=True, help_text='IP where RouterOS API login succeeded during Connect.', null=True, protocol='IPv4'),
        ),
    ]
