# Generated by Django 4.2.30 on 2026-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo', null=True, upload_to='profiles/%Y/%m/'),
        ),
    ]
