# Generated by Django 4.2.30 on 2026-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending role allocation'), ('super_admin', 'Super admin'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('it_support', 'IT support'), ('sales', 'Sales'), ('technician', 'Technician')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('burned', 'Burned')], db_index=True, default='pending_approval', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
