# Generated by Django 4.2.30 on 2026-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_status_role_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending role allocation'), ('super_admin', 'Super admin'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('it_support', 'IT support'), ('sales', 'Sales'), ('technician', 'Technician')], db_index=True, default='pending', help_text='Assigned employee role', max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('burned', 'Burned')], db_index=True, default='pending_approval', help_text='Employee account status', max_length=32),
        ),
    ]
