# Generated by Django 4.2.30 on 2026-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employee_status_role_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='registered', help_text='Set to Registered when the organization submits registration details', max_length=20),
        ),
    ]
