# Generated by Django 5.0.14 on 2026-07-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organization_mpesa_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Turn on the platform payment gateway for subscription collections.', verbose_name='Enabled')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20, verbose_name='Provider')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='Environment')),
                ('payment_type', models.CharField(blank=True, choices=[('', 'Not set'), ('paybill', 'Paybill'), ('till', 'Buy Goods Till')], default='', help_text='Paybill or Buy Goods Till used by the platform.', max_length=20, verbose_name='Payment type')),
                ('shortcode', models.CharField(blank=True, help_text='Paybill number or Buy Goods Till number.', max_length=20, verbose_name='Shortcode')),
                ('account_reference', models.CharField(blank=True, help_text='Optional Paybill account / reference.', max_length=64, verbose_name='Account reference')),
                ('consumer_key', models.CharField(blank=True, max_length=255, verbose_name='Consumer key')),
                ('consumer_secret', models.CharField(blank=True, max_length=255, verbose_name='Consumer secret')),
                ('passkey', models.CharField(blank=True, max_length=255, verbose_name='Passkey')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment gateway',
                'verbose_name_plural': 'Payment gateway',
                'db_table': 'accounts_payment_gateway',
            },
        ),
    ]
