# Generated by Django 5.0.14 on 2026-07-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='callback_url',
            field=models.URLField(blank=True, help_text='HTTPS URL Safaricom will call with STK Push payment results.', max_length=500, verbose_name='Callback URL'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='account_reference',
            field=models.CharField(blank=True, help_text='Optional default AccountReference sent with STK Push (Paybill).', max_length=64, verbose_name='Default account reference'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Turn on M-Pesa Daraja Lipa Na M-Pesa Online (STK Push) for collections.', verbose_name='Activate STK Push'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='passkey',
            field=models.CharField(blank=True, help_text='Passkey for the Lipa Na M-Pesa Online shortcode.', max_length=255, verbose_name='Lipa Na M-Pesa passkey'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('paybill', 'Paybill'), ('till', 'Buy Goods Till')], default='', help_text='Paybill (CustomerPayBillOnline) or Till (CustomerBuyGoodsOnline).', max_length=20, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='shortcode',
            field=models.CharField(blank=True, help_text='Lipa Na M-Pesa Online shortcode (Paybill or Till).', max_length=20, verbose_name='Business shortcode'),
        ),
    ]
