# Generated by Django 5.0.14 on 2026-07-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_payment_gateway_stk_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='account_reference',
            field=models.CharField(blank=True, help_text="Unused. STK Push AccountReference is always the client's account number.", max_length=64, verbose_name='Account reference'),
        ),
    ]
