# Generated by Django 5.0.14 on 2026-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_payment_gateway_client_account_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL Safaricom calls with STK Push results. Sandbox may use http://localhost:8000; production requires HTTPS.', max_length=500, verbose_name='Callback URL'),
        ),
    ]
