# Generated by Django 5.0.14 on 2026-07-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_payment_gateway_sandbox_localhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='daraja_consumer_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Daraja consumer key'),
        ),
        migrations.AddField(
            model_name='organization',
            name='daraja_consumer_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Daraja consumer secret'),
        ),
        migrations.AddField(
            model_name='organization',
            name='daraja_enabled',
            field=models.BooleanField(default=False, help_text='Receive subscription payments via M-Pesa Daraja STK Push.', verbose_name='Enable Daraja API'),
        ),
        migrations.AddField(
            model_name='organization',
            name='daraja_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='Daraja environment'),
        ),
        migrations.AddField(
            model_name='organization',
            name='daraja_passkey',
            field=models.CharField(blank=True, help_text='Passkey for your Paybill or Till Lipa Na M-Pesa Online shortcode.', max_length=255, verbose_name='Lipa Na M-Pesa passkey'),
        ),
    ]
