# Generated by Django 5.0.14 on 2026-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_hotspot_welcome_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='pppoe_compulsory',
            field=models.BooleanField(default=False, help_text='When enabled, free LAN browsing is blocked. Dialed PPPoE clients keep internet; other devices can use Hotspot when it is enabled.', verbose_name='PPPoE enforcement'),
        ),
    ]
