# Generated by Django 5.0.14 on 2026-08-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_mikrotik_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='hotspot_enabled',
            field=models.BooleanField(default=False, help_text='Allow Hotspot portals and voucher access for this organization. Enabled automatically as fallback when PPPoE enforcement is on.', verbose_name='Enable Hotspot'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='pppoe_compulsory',
            field=models.BooleanField(default=False, help_text='When enabled, free LAN browsing is blocked. Paid PPPoE clients surf automatically; other devices fall back to the Hotspot payment portal.', verbose_name='PPPoE enforcement'),
        ),
    ]
