# Generated by Django 5.0.14 on 2026-08-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customer_hotspot_mac_unique'),
        ('billing', '0018_customer_usage_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('customer_category', models.CharField(choices=[('home', 'Home internet'), ('business', 'Business internet')], db_index=True, default='home', max_length=20)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name / company name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone / company number')),
                ('alternative_phone', models.CharField(blank=True, max_length=30, verbose_name='Alternative phone / company number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_type', models.CharField(choices=[('home_internet', 'Home internet'), ('business_internet', 'Business internet'), ('dedicated_link', 'Dedicated link'), ('starlink_installation', 'Starlink installation'), ('hotspot', 'Hotspot')], db_index=True, default='home_internet', max_length=32)),
                ('lead_source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone_call', 'Phone call'), ('referral', 'Referral'), ('website', 'Website'), ('social_media', 'Social media'), ('field_visit', 'Field visit'), ('other', 'Other')], default='walk_in', max_length=32)),
                ('customer_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Sales organization that owns this lead', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.organization')),
                ('preferred_isp', models.ForeignKey(blank=True, help_text='Optional preferred ISP from registered organizations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_leads', to='accounts.organization')),
                ('preferred_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='billing.billingplan')),
            ],
            options={
                'db_table': 'accounts_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
