# Generated by Django 5.0.14 on 2026-08-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='preferred_installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Preferred installation date'),
        ),
    ]
