# Generated by Django 5.0.14 on 2026-08-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_lead_preferred_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='customer_category',
            field=models.CharField(choices=[('home', 'Home internet'), ('business', 'Business internet'), ('isp_client', 'ISP client'), ('hotspot_client', 'Hotspot client')], db_index=True, default='home', max_length=20),
        ),
    ]
