# Generated by Django 5.0.14 on 2026-08-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_sales_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Sales organization that owns this lead (optional until an ISP is chosen).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.organization'),
        ),
    ]
