# Generated by Django 5.0.14 on 2026-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_lead_organization_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='ISPCENTRIC', help_text='Brand name shown across the platform.', max_length=120, verbose_name='App name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp number')),
                ('logo', models.ImageField(blank=True, help_text='Company logo shown in the workspace.', null=True, upload_to='company/%Y/%m/', verbose_name='Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company profile',
                'verbose_name_plural': 'Company profile',
                'db_table': 'accounts_company_profile',
            },
        ),
    ]
