# Generated by Django 5.0.14 on 2026-08-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pending', 'Pending role allocation'), ('super_admin', 'Super admin'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('it_support', 'IT support'), ('sales', 'Sales'), ('technician', 'Technician')], db_index=True, max_length=32, unique=True, verbose_name='Role')),
                ('enabled', models.BooleanField(default=False, help_text='Turn on commission tracking for this role.', verbose_name='Enable commissions')),
                ('rate_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat amount')], default='percent', max_length=16, verbose_name='Rate type')),
                ('rate_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (e.g. 5.00) or flat amount in KES.', max_digits=10, verbose_name='Rate value')),
                ('notes', models.CharField(blank=True, help_text='Optional note about how this commission is calculated.', max_length=255, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role commission',
                'verbose_name_plural': 'Role commissions',
                'db_table': 'accounts_role_commission',
                'ordering': ['role'],
            },
        ),
    ]
