# Generated by Django 5.0.14 on 2026-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_role_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecommission',
            name='rate_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat amount'), ('per_ticket', 'Per ticket')], default='percent', max_length=16, verbose_name='Rate type'),
        ),
        migrations.AlterField(
            model_name='rolecommission',
            name='rate_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage, flat amount, or price per ticket in KES.', max_digits=10, verbose_name='Rate value'),
        ),
    ]
