# Generated by Django 5.0.14 on 2026-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_role_commission_per_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecommission',
            name='rate_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat amount'), ('per_ticket', 'Per ticket'), ('per_ticket_package', 'Per ticket package %')], default='percent', max_length=32, verbose_name='Rate type'),
        ),
    ]
