# Generated by Django 5.0.14 on 2026-08-02 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_role_commission_package_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending role allocation'), ('super_admin', 'Super admin'), ('administrator', 'Administrator'), ('manager', 'Customer support'), ('it_support', 'IT support'), ('sales', 'Sales'), ('technician', 'Technician')], db_index=True, default='pending', help_text='Assigned employee role', max_length=32),
        ),
        migrations.AlterField(
            model_name='rolecommission',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending role allocation'), ('super_admin', 'Super admin'), ('administrator', 'Administrator'), ('manager', 'Customer support'), ('it_support', 'IT support'), ('sales', 'Sales'), ('technician', 'Technician')], db_index=True, max_length=32, unique=True, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Equipment name')),
                ('equipment_type', models.CharField(choices=[('router', 'Router'), ('onu', 'ONU / ONT'), ('switch', 'Switch'), ('radio', 'Radio / antenna'), ('cable', 'Cable'), ('connector', 'Connector / splitter'), ('power', 'Power / PoE'), ('other', 'Other')], db_index=True, default='router', max_length=20, verbose_name='Type')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial number')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('faulty', 'Faulty'), ('retired', 'Retired')], db_index=True, default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_network_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network equipment',
                'verbose_name_plural': 'Network equipment',
                'db_table': 'accounts_network_equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
