# Generated by Django 5.0.14 on 2026-08-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_network_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee this equipment is currently allocated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_equipment', to='accounts.employee'),
        ),
    ]
