# Generated by Django 5.0.14 on 2026-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_network_equipment_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkequipment',
            name='allocated_at',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='status',
        ),
    ]
