# Generated by Django 5.0.14 on 2026-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_network_equipment_simplify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current units in stock.', verbose_name='Stock quantity'),
        ),
    ]
