# Generated by Django 5.0.14 on 2026-08-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_network_equipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
    ]
