# Generated by Django 5.0.14 on 2026-08-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_network_equipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEquipmentSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=120, verbose_name='Serial number')),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('issued', 'Issued')], db_index=True, default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_equipment_serials', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='accounts.networkequipment')),
            ],
            options={
                'verbose_name': 'Equipment serial',
                'verbose_name_plural': 'Equipment serials',
                'db_table': 'accounts_network_equipment_serial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkequipmentserial',
            constraint=models.UniqueConstraint(fields=('equipment', 'serial_number'), name='uniq_equipment_serial_number'),
        ),
    ]
