# Generated by Django 5.0.14 on 2026-08-03 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_client_settings_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Shareable code derived from company name and phone number.', max_length=64, null=True, unique=True, verbose_name='Referral code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='ISP that referred this organization via a referral link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.organization'),
        ),
    ]
