# Generated by Django 6.1 on 2026-08-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_networkequipment_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Send SMS notifications to clients using your gateway.', verbose_name='Enable SMS')),
                ('sms_provider', models.CharField(blank=True, choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('custom', 'Custom HTTP API')], default='africastalking', max_length=32, verbose_name='SMS provider')),
                ('sms_username', models.CharField(blank=True, help_text="Africa's Talking username or Twilio Account SID.", max_length=120, verbose_name='SMS username / Account SID')),
                ('sms_api_key', models.CharField(blank=True, help_text="Africa's Talking API key, Twilio Auth Token, or custom API key.", max_length=512, verbose_name='SMS API key / Auth token')),
                ('sms_sender_id', models.CharField(blank=True, help_text="Alphanumeric sender ID or shortcode (Africa's Talking / custom).", max_length=32, verbose_name='SMS sender ID')),
                ('sms_from_number', models.CharField(blank=True, help_text='Twilio phone number that sends SMS, e.g. +2547…', max_length=30, verbose_name='SMS from number')),
                ('sms_base_url', models.URLField(blank=True, help_text='POST endpoint for a custom SMS gateway.', max_length=500, verbose_name='Custom SMS API URL')),
                ('email_enabled', models.BooleanField(default=False, help_text='Send email using your own SMTP account.', verbose_name='Enable email')),
                ('email_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com or mail.yourdomain.com', max_length=255, verbose_name='SMTP host')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='587 for TLS, 465 for SSL, 25 for unencrypted.', verbose_name='SMTP port')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Turn on for port 587. Port 465 uses SSL automatically.', verbose_name='Use TLS')),
                ('email_host_user', models.CharField(blank=True, help_text='Usually the full email address you sign in with.', max_length=255, verbose_name='SMTP username')),
                ('email_host_password', models.CharField(blank=True, help_text='App password or mailbox password.', max_length=512, verbose_name='SMTP password')),
                ('email_from_email', models.EmailField(blank=True, help_text='Address clients see as the sender. Defaults to the SMTP username.', max_length=254, verbose_name='From email')),
                ('email_from_name', models.CharField(blank=True, help_text='Display name, e.g. your ISP name.', max_length=120, verbose_name='From name')),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text='Send WhatsApp messages using your Business API.', verbose_name='Enable WhatsApp')),
                ('whatsapp_provider', models.CharField(blank=True, choices=[('meta', 'WhatsApp Cloud API (Meta)'), ('twilio', 'Twilio WhatsApp'), ('africastalking', "Africa's Talking WhatsApp")], default='meta', max_length=32, verbose_name='WhatsApp provider')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='From Meta WhatsApp Cloud API.', max_length=64, verbose_name='WhatsApp phone number ID')),
                ('whatsapp_access_token', models.CharField(blank=True, help_text='Permanent or temporary Meta Cloud API token.', max_length=1024, verbose_name='WhatsApp access token')),
                ('whatsapp_username', models.CharField(blank=True, help_text="Twilio Account SID or Africa's Talking username.", max_length=120, verbose_name='WhatsApp username / Account SID')),
                ('whatsapp_api_key', models.CharField(blank=True, help_text="Twilio Auth Token or Africa's Talking API key.", max_length=512, verbose_name='WhatsApp API key / Auth token')),
                ('whatsapp_from_number', models.CharField(blank=True, help_text='Business number that sends WhatsApp, e.g. +2547…', max_length=30, verbose_name='WhatsApp from number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Communication settings',
                'verbose_name_plural': 'Communication settings',
                'db_table': 'accounts_communication_settings',
            },
        ),
    ]
