# Generated by Django 6.1 on 2026-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_platform_communication_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='daraja_environment',
            field=models.CharField(choices=[('sandbox', 'Company Payment Gateway'), ('production', 'My own Payment Gateway')], default='sandbox', max_length=20, verbose_name='STK gateway'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Company Daraja STK Push. Default for ISPs without their own Payment Gateway, and for platform fees such as MikroTik onboarding.', verbose_name='Activate STK Push'),
        ),
    ]
