# Generated by Django 6.1 on 2026-08-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_organization_daraja_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL Safaricom calls with STK Push results. Sandbox accepts local (http://localhost) or hosted (https://…) URLs. Production requires HTTPS.', max_length=500, verbose_name='Callback URL'),
        ),
    ]
