# Generated by Django 6.1 on 2026-08-30 18:06

import django.db.models.deletion
import ispcentric.encrypted_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_paymentgateway_callback_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsettings',
            name='email_host_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='App password or mailbox password.', max_length=1024, verbose_name='SMTP password'),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='sms_api_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text="Africa's Talking API key, Twilio Auth Token, or custom API key.", max_length=1024, verbose_name='SMS API key / Auth token'),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='whatsapp_access_token',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='Permanent or temporary Meta Cloud API token.', max_length=2048, verbose_name='WhatsApp access token'),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='whatsapp_api_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text="Twilio Auth Token or Africa's Talking API key.", max_length=1024, verbose_name='WhatsApp API key / Auth token'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='daraja_consumer_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Daraja consumer key'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='daraja_consumer_secret',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Daraja consumer secret'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='daraja_passkey',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='Passkey for your Paybill or Till Lipa Na M-Pesa Online shortcode.', max_length=512, verbose_name='Lipa Na M-Pesa passkey'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='consumer_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Consumer key'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='consumer_secret',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Consumer secret'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='passkey',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='Passkey for the Lipa Na M-Pesa Online shortcode.', max_length=512, verbose_name='Lipa Na M-Pesa passkey'),
        ),
        migrations.AlterField(
            model_name='platformcommunicationsettings',
            name='email_host_password',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='App password or mailbox password.', max_length=1024, verbose_name='SMTP password'),
        ),
        migrations.AlterField(
            model_name='platformcommunicationsettings',
            name='sms_api_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text="Africa's Talking API key, Twilio Auth Token, or custom API key.", max_length=1024, verbose_name='SMS API key / Auth token'),
        ),
        migrations.AlterField(
            model_name='platformcommunicationsettings',
            name='whatsapp_access_token',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text='Permanent or temporary Meta Cloud API token.', max_length=2048, verbose_name='WhatsApp access token'),
        ),
        migrations.AlterField(
            model_name='platformcommunicationsettings',
            name='whatsapp_api_key',
            field=ispcentric.encrypted_fields.EncryptedCharField(blank=True, help_text="Twilio Auth Token or Africa's Talking API key.", max_length=1024, verbose_name='WhatsApp API key / Auth token'),
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('actor_ip', models.CharField(blank=True, default='', max_length=64)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security audit log',
                'verbose_name_plural': 'Security audit logs',
                'db_table': 'accounts_security_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
