# Generated by Django 6.1 on 2026-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_organization_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='login_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='6-digit code the ISP owner uses to log in (separate from staff login codes).', max_length=6, unique=True),
        ),
    ]
