# Generated by Django 5.0.14 on 2026-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_organization_adverts_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='adverts_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, Hotspot and PPPoE pay / pause pages show a “Click to earn” link for this ISP.', verbose_name='Show Click to earn on captive pages'),
        ),
    ]
