# Generated by Django 4.2.30 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0049_customer_status_in_progress_pending_activation"),
        ("accounts", "0058_organization_hotspot_welcome_link_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotspotPortalClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earn", "Refer & earn"),
                            ("partner_1", "Partner link 1"),
                            ("partner_2", "Partner link 2"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "contact_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable contact id (MAC, phone, or anonymous session).",
                        max_length=80,
                    ),
                ),
                ("hotspot_mac", models.CharField(blank=True, default="", max_length=32)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("display_name", models.CharField(blank=True, default="", max_length=150)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("first_clicked_at", models.DateTimeField(auto_now_add=True)),
                ("last_clicked_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotspot_portal_clicks",
                        to="billing.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_portal_clicks",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_hotspot_portal_click",
                "ordering": ["-last_clicked_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="hotspotportalclick",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "contact_key"),
                name="hs_portal_click_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="hotspotportalclick",
            index=models.Index(
                fields=["organization", "contact_key"],
                name="hs_portal_click_org_ck",
            ),
        ),
    ]
