# Generated by Django 5.0.14 on 2026-09-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_hotspot_portal_click'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEquipmentStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock in'), ('stock_out', 'Stock out'), ('allocate', 'Allocated'), ('return', 'Returned')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_stock_movements_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_stock_movements', to='accounts.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.networkequipment')),
            ],
            options={
                'verbose_name': 'Equipment stock movement',
                'verbose_name_plural': 'Equipment stock movements',
                'db_table': 'accounts_network_equipment_stock_movement',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
