# Generated by Django 5.0.14 on 2026-09-08 10:19

from django.db import migrations, models


def preserve_existing_own_credentials(apps, schema_editor):
    CommunicationSettings = apps.get_model("accounts", "CommunicationSettings")
    for row in CommunicationSettings.objects.all().iterator():
        updates = {}
        if (row.sms_username or "").strip() and (row.sms_api_key or "").strip():
            updates["sms_credential_source"] = "own"
        elif (row.sms_base_url or "").strip() and (row.sms_api_key or "").strip():
            updates["sms_credential_source"] = "own"
        if (
            (row.email_host or "").strip()
            and (row.email_host_user or "").strip()
            and (row.email_host_password or "").strip()
        ):
            updates["email_credential_source"] = "own"
        if (row.whatsapp_access_token or "").strip() or (
            (row.whatsapp_username or "").strip() and (row.whatsapp_api_key or "").strip()
        ):
            updates["whatsapp_credential_source"] = "own"
        if updates:
            CommunicationSettings.objects.filter(pk=row.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_fault_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationsettings",
            name="email_credential_source",
            field=models.CharField(
                choices=[
                    ("company", "Company communications"),
                    ("own", "My own credentials"),
                ],
                default="company",
                help_text=(
                    "Company communications is the default (IT Support). "
                    "Switch to My own credentials when ready."
                ),
                max_length=20,
                verbose_name="Email credentials",
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="sms_credential_source",
            field=models.CharField(
                choices=[
                    ("company", "Company communications"),
                    ("own", "My own credentials"),
                ],
                default="company",
                help_text=(
                    "Company communications is the default (IT Support). "
                    "Switch to My own credentials when ready."
                ),
                max_length=20,
                verbose_name="SMS credentials",
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="whatsapp_credential_source",
            field=models.CharField(
                choices=[
                    ("company", "Company communications"),
                    ("own", "My own credentials"),
                ],
                default="company",
                help_text=(
                    "Company communications is the default (IT Support). "
                    "Switch to My own credentials when ready."
                ),
                max_length=20,
                verbose_name="WhatsApp credentials",
            ),
        ),
        migrations.RunPython(
            preserve_existing_own_credentials,
            migrations.RunPython.noop,
        ),
    ]
