# Generated by Django 5.0.14 on 2026-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_communication_credential_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformcommunicationsettings",
            name="enabled_messages",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Map of platform event keys to selected channels "
                    '(e.g. {"platform_isp_welcome": ["email", "sms"]}).'
                ),
                verbose_name="Enabled messages",
            ),
        ),
    ]
