# Generated by Django 5.0.14 on 2026-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_clientsettings_google_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcommunicationsettings',
            name='enabled_messages',
            field=models.JSONField(blank=True, default=dict, help_text='Map of platform event keys to rule objects with message, recipients, and channels (e.g. {"platform_isp_welcome": {"message": "...", "recipients": ["new_isp_owner"], "channels": ["email", "sms"]}}).', verbose_name='Enabled messages'),
        ),
    ]
